name:                hzip
version:             0.1.0.0
github:              "wonhyukchoi/hzip"
license:             BSD3
author:              "Wonhyuk Choi"
maintainer:          "wonhyuk.com"
copyright:           "2023 Wonhyuk Choi"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            A pure Haskell file compressor / decompressor using the DEFLATE algorithm.
# category:            Compression

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wonhyukchoi/hzip#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hzip-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hzip
    - optparse-applicative

tests:
  hzip-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hzip
